name: Test
on:
  push:
    branches:
      - master
      - demo-github-action
  pull_request:
jobs:

  test-github-action:
    name: "[core] github action"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: '3.0.0'
      # name: Build orlangure/gnomock image
      # run: task gnomock:build:server
      - name: Start Gnomock server
        uses: gnomock/github-action@master
      - name: Test Gnomock connection
        run: curl 127.0.0.1:23042/start/mongo -d '{}'
      - name: Test Gnomock started service connection
        run: nc -z 127.0.0.1 $(curl 127.0.0.1:23042/start/mongo -d '{}' | jq .ports.default.port)
